// This file will be auto-generated by Supabase CLI in production.
// Run: npx supabase gen types typescript --local > src/types/supabase.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

interface ProfileRow {
  id: string;
  user_id: string;
  business_name: string | null;
  business_type: string | null;
  timezone: string;
  phone: string | null;
  website: string | null;
  ai_enabled: boolean;
  subscription_tier: string;
  role: string;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  hubspot_portal_id: string | null;
  hubspot_access_token: string | null;
  hubspot_refresh_token: string | null;
  meta_page_id: string | null;
  meta_access_token: string | null;
  twilio_account_sid: string | null;
  twilio_auth_token: string | null;
  twilio_phone_number: string | null;
  vapi_api_key: string | null;
  anthropic_api_key: string | null;
  sendgrid_api_key: string | null;
  stripe_secret_key: string | null;
  google_calendar_token: Json | null;
  outlook_calendar_token: Json | null;
  ai_confidence_threshold: number;
  require_approval: boolean;
  ai_memory_depth: number;
  training_data_opt_out: boolean;
  default_language: string;
  slack_webhook_url: string | null;
  slack_notify_hot_leads: boolean | null;
  slack_notify_bookings: boolean | null;
  stale_lead_hours: number | null;
  referral_code: string | null;
  referred_by_code: string | null;
  hide_branding: boolean | null;
  created_at: string;
  updated_at: string;
}

interface AIApprovalRow {
  id: string;
  user_id: string;
  conversation_id: string | null;
  contact_id: string | null;
  draft_content: string;
  confidence: number | null;
  reasoning: string | null;
  status: string;
  approved_by: string | null;
  approved_at: string | null;
  created_at: string;
}

interface TeamMemberRow {
  id: string;
  owner_id: string;
  member_user_id: string;
  role: string;
  created_at: string;
  updated_at: string;
}

interface TeamInvitationRow {
  id: string;
  owner_id: string;
  email: string;
  role: string;
  token: string;
  status: string;
  expires_at: string;
  accepted_at: string | null;
  created_at: string;
}

interface ContactRow {
  id: string;
  user_id: string;
  name: string | null;
  email: string | null;
  phone: string | null;
  company: string | null;
  source_channel: string | null;
  status: string;
  temperature: string;
  last_interaction_at: string | null;
  hubspot_contact_id: string | null;
  hubspot_deal_id: string | null;
  metadata: Json;
  opted_out: boolean;
  opt_out_at: string | null;
  tags: string[];
  score: number;
  assigned_to: string | null;
  created_at: string;
  updated_at: string;
}

interface ChannelRow {
  id: string;
  user_id: string;
  type: string;
  name: string;
  is_active: boolean;
  config: Json;
  webhook_secret: string | null;
  created_at: string;
  updated_at: string;
}

interface ConversationRow {
  id: string;
  user_id: string;
  contact_id: string;
  channel_id: string | null;
  channel_type: string;
  status: string;
  is_ai_active: boolean;
  ai_handoff_reason: string | null;
  handoff_at: string | null;
  external_thread_id: string | null;
  summary: string | null;
  sentiment: string;
  intent: string | null;
  last_message_at: string | null;
  unread_count: number;
  metadata: Json;
  created_at: string;
  updated_at: string;
}

interface MessageRow {
  id: string;
  user_id: string;
  conversation_id: string;
  contact_id: string;
  direction: string;
  sender_type: string;
  content: string | null;
  content_type: string;
  channel_type: string;
  external_message_id: string | null;
  media_url: string | null;
  media_storage_path: string | null;
  ai_model: string | null;
  ai_confidence: number | null;
  ai_tokens_used: number | null;
  metadata: Json;
  delivered_at: string | null;
  read_at: string | null;
  created_at: string;
}

interface KnowledgeBaseRow {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

interface KnowledgeDocumentRow {
  id: string;
  user_id: string;
  knowledge_base_id: string;
  title: string;
  file_name: string | null;
  file_type: string | null;
  storage_path: string | null;
  content_text: string | null;
  chunk_count: number;
  status: string;
  error_message: string | null;
  metadata: Json;
  created_at: string;
  updated_at: string;
}

interface KnowledgeChunkRow {
  id: string;
  user_id: string;
  document_id: string;
  knowledge_base_id: string;
  content: string;
  embedding: unknown;
  chunk_index: number;
  token_count: number | null;
  metadata: Json;
  created_at: string;
}

interface AIAgentConfigRow {
  id: string;
  user_id: string;
  agent_type: string;
  name: string;
  system_prompt: string | null;
  enabled: boolean;
  model: string;
  max_tokens: number;
  temperature: number;
  tools_enabled: string[];
  knowledge_base_ids: string[];
  config: Json;
  created_at: string;
  updated_at: string;
}

interface AIInteractionLogRow {
  id: string;
  user_id: string;
  conversation_id: string | null;
  message_id: string | null;
  agent_type: string;
  input_tokens: number | null;
  output_tokens: number | null;
  model: string | null;
  latency_ms: number | null;
  tools_called: Json;
  reasoning: string | null;
  error: string | null;
  created_at: string;
}

interface SubscriptionRow {
  id: string;
  user_id: string;
  stripe_subscription_id: string | null;
  stripe_customer_id: string | null;
  plan: string;
  status: string;
  current_period_start: string | null;
  current_period_end: string | null;
  message_count_this_period: number;
  message_limit: number;
  ai_calls_this_period: number;
  ai_calls_limit: number;
  created_at: string;
  updated_at: string;
}

interface AnalyticsEventRow {
  id: string;
  user_id: string;
  event_type: string;
  contact_id: string | null;
  conversation_id: string | null;
  channel_type: string | null;
  metadata: Json;
  created_at: string;
}

interface WebhookLogRow {
  id: string;
  user_id: string | null;
  source: string;
  event_type: string | null;
  payload: Json | null;
  status: string;
  error: string | null;
  processed_at: string | null;
  created_at: string;
}

interface ServiceRow {
  id: string;
  user_id: string;
  name: string;
  description: string | null;
  duration_minutes: number;
  price_cents: number;
  currency: string;
  is_active: boolean;
  color: string;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

interface AvailabilityScheduleRow {
  id: string;
  user_id: string;
  day_of_week: number;
  start_time: string;
  end_time: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

interface BlockedDateRow {
  id: string;
  user_id: string;
  blocked_date: string;
  reason: string | null;
  all_day: boolean;
  start_time: string | null;
  end_time: string | null;
  created_at: string;
}

interface BookingSettingsRow {
  id: string;
  user_id: string;
  booking_url_slug: string | null;
  business_name: string | null;
  business_description: string | null;
  logo_url: string | null;
  min_notice_hours: number;
  max_advance_days: number;
  slot_duration_minutes: number;
  buffer_minutes: number;
  require_payment: boolean;
  deposit_amount_cents: number;
  confirmation_message: string;
  cancellation_policy: string | null;
  timezone: string;
  allowed_areas: string[];
  created_at: string;
  updated_at: string;
}

interface BookingRow {
  id: string;
  user_id: string;
  service_id: string | null;
  contact_id: string | null;
  client_name: string;
  client_email: string;
  client_phone: string | null;
  booking_date: string;
  start_time: string;
  end_time: string;
  status: string;
  notes: string | null;
  internal_notes: string | null;
  location: string | null;
  area: string | null;
  payment_status: string;
  payment_amount_cents: number;
  stripe_payment_intent_id: string | null;
  stripe_checkout_session_id: string | null;
  cancellation_reason: string | null;
  cancelled_at: string | null;
  confirmed_at: string | null;
  completed_at: string | null;
  reminder_sent_at: string | null;
  metadata: Json;
  created_at: string;
  updated_at: string;
}

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow;
        Insert: Partial<ProfileRow> & { user_id: string };
        Update: Partial<ProfileRow>;
        Relationships: [];
      };
      contacts: {
        Row: ContactRow;
        Insert: Partial<ContactRow> & { user_id: string };
        Update: Partial<ContactRow>;
        Relationships: [];
      };
      channels: {
        Row: ChannelRow;
        Insert: Partial<ChannelRow> & { user_id: string; type: string; name: string };
        Update: Partial<ChannelRow>;
        Relationships: [];
      };
      conversations: {
        Row: ConversationRow;
        Insert: Partial<ConversationRow> & { user_id: string; contact_id: string; channel_type: string };
        Update: Partial<ConversationRow>;
        Relationships: [];
      };
      messages: {
        Row: MessageRow;
        Insert: Partial<MessageRow> & { user_id: string; conversation_id: string; contact_id: string; direction: string; sender_type: string; channel_type: string };
        Update: Partial<MessageRow>;
        Relationships: [];
      };
      knowledge_bases: {
        Row: KnowledgeBaseRow;
        Insert: Partial<KnowledgeBaseRow> & { user_id: string; name: string };
        Update: Partial<KnowledgeBaseRow>;
        Relationships: [];
      };
      knowledge_documents: {
        Row: KnowledgeDocumentRow;
        Insert: Partial<KnowledgeDocumentRow> & { user_id: string; knowledge_base_id: string; title: string };
        Update: Partial<KnowledgeDocumentRow>;
        Relationships: [];
      };
      knowledge_chunks: {
        Row: KnowledgeChunkRow;
        Insert: Partial<KnowledgeChunkRow> & { user_id: string; document_id: string; knowledge_base_id: string; content: string; chunk_index: number };
        Update: Partial<KnowledgeChunkRow>;
        Relationships: [];
      };
      ai_agent_configs: {
        Row: AIAgentConfigRow;
        Insert: Partial<AIAgentConfigRow> & { user_id: string; agent_type: string; name: string };
        Update: Partial<AIAgentConfigRow>;
        Relationships: [];
      };
      ai_interaction_logs: {
        Row: AIInteractionLogRow;
        Insert: Partial<AIInteractionLogRow> & { user_id: string; agent_type: string };
        Update: Partial<AIInteractionLogRow>;
        Relationships: [];
      };
      subscriptions: {
        Row: SubscriptionRow;
        Insert: Partial<SubscriptionRow> & { user_id: string };
        Update: Partial<SubscriptionRow>;
        Relationships: [];
      };
      analytics_events: {
        Row: AnalyticsEventRow;
        Insert: Partial<AnalyticsEventRow> & { user_id: string; event_type: string };
        Update: Partial<AnalyticsEventRow>;
        Relationships: [];
      };
      webhook_logs: {
        Row: WebhookLogRow;
        Insert: Partial<WebhookLogRow> & { source: string };
        Update: Partial<WebhookLogRow>;
        Relationships: [];
      };
      team_members: {
        Row: TeamMemberRow;
        Insert: Partial<TeamMemberRow> & { owner_id: string; member_user_id: string };
        Update: Partial<TeamMemberRow>;
        Relationships: [];
      };
      team_invitations: {
        Row: TeamInvitationRow;
        Insert: Partial<TeamInvitationRow> & { owner_id: string; email: string };
        Update: Partial<TeamInvitationRow>;
        Relationships: [];
      };
      services: {
        Row: ServiceRow;
        Insert: Partial<ServiceRow> & { user_id: string; name: string };
        Update: Partial<ServiceRow>;
        Relationships: [];
      };
      availability_schedules: {
        Row: AvailabilityScheduleRow;
        Insert: Partial<AvailabilityScheduleRow> & { user_id: string; day_of_week: number; start_time: string; end_time: string };
        Update: Partial<AvailabilityScheduleRow>;
        Relationships: [];
      };
      blocked_dates: {
        Row: BlockedDateRow;
        Insert: Partial<BlockedDateRow> & { user_id: string; blocked_date: string };
        Update: Partial<BlockedDateRow>;
        Relationships: [];
      };
      booking_settings: {
        Row: BookingSettingsRow;
        Insert: Partial<BookingSettingsRow> & { user_id: string };
        Update: Partial<BookingSettingsRow>;
        Relationships: [];
      };
      bookings: {
        Row: BookingRow;
        Insert: Partial<BookingRow> & { user_id: string; client_name: string; client_email: string; booking_date: string; start_time: string; end_time: string };
        Update: Partial<BookingRow>;
        Relationships: [];
      };
      ai_approvals: {
        Row: AIApprovalRow;
        Insert: Partial<AIApprovalRow> & { user_id: string; draft_content: string };
        Update: Partial<AIApprovalRow>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      match_knowledge_chunks: {
        Args: {
          query_embedding: unknown;
          match_threshold?: number;
          match_count?: number;
          p_knowledge_base_id?: string;
          p_user_id?: string;
        };
        Returns: {
          id: string;
          content: string;
          document_id: string;
          chunk_index: number;
          similarity: number;
        }[];
      };
      match_knowledge_chunks_for_user: {
        Args: {
          query_embedding: unknown;
          p_user_id: string;
          match_threshold?: number;
          match_count?: number;
          p_knowledge_base_id?: string | null;
        };
        Returns: {
          id: string;
          content: string;
          document_id: string;
          chunk_index: number;
          similarity: number;
        }[];
      };
      increment_message_count: {
        Args: { p_user_id: string };
        Returns: undefined;
      };
      increment_ai_call_count: {
        Args: { p_user_id: string };
        Returns: undefined;
      };
      get_public_booking_settings: {
        Args: { p_slug: string };
        Returns: BookingSettingsRow[];
      };
    };
    Enums: Record<string, never>;
  };
};
